version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
    - usetesting
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: indent-error-flow
        - name: errorf
        - name: context-as-argument
        - name: context-keys-type
        - name: early-return
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
